[project]
name = "garmin-intensity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "garminconnect>=0.2.38",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
]
